version: "3"
services:
  jenkins:
    build: .
    ports:
     - "5000:8080"
     - "5001:50000"
    volumes:
     - simplest-sync:/var/jenkins_home:nocopy
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
volumes:
  simplest-sync:
    external: true
